version: '3'
services:
  backend:
    build: ./backend
    command: npx nodemon --legacy-watch index.js
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: development
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3003:3000"
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sobaka282001
      MYSQL_DATABASE: lx_store
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - frontend
