version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
  frontend:
    build: ./frontend
    ports:
      - "3003:3000"
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
